version: "3.9"

services:
  kakigori-app:
    build: .
    container_name: kakigori-app
    ports:
      - "8501:8501"
    volumes:
      - ./feedback:/app/feedback          # lưu feedback ra ngoài
      - ./tmp_upload:/app/tmp_upload      # lưu video upload tạm
    environment:
      - TZ=UTC
      - YOLO_CONFIG_DIR=/app/.yolo_cfg
      # GPU: uncomment dòng dưới và cài NVIDIA Container Toolkit
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]